[tox]
envlist =
    py{310,311}-django{42,51,52}
    py{312,313}-django{42,51,52,60}
skip_missing_interpreters = true
[testenv]
deps =
    -rrequirements.txt
    -rtest_requirements.txt
    django42: Django>=4.2,<4.3
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
commands=
    pytest
